-- English Space for Polina
-- Run this file in the Supabase SQL Editor as a project owner.

create extension if not exists pgcrypto;

create table if not exists public.homework_progress (
  id bigint generated by default as identity primary key,
  submission_id uuid not null unique default gen_random_uuid(),
  student_id text not null,
  lesson_id text not null,
  status text not null default 'draft',
  answers jsonb not null default '{}'::jsonb,
  score_correct integer,
  score_total integer,
  score_percent integer,
  checked_at timestamptz,
  submitted_at timestamptz,
  locked_at timestamptz,
  report_status text not null default 'not_sent',
  report_sent_at timestamptz,
  report_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint homework_progress_student_lesson_key unique (student_id, lesson_id),
  constraint homework_progress_status_check check (status in ('draft', 'submitted_pending_report', 'submitted')),
  constraint homework_progress_report_status_check check (report_status in ('not_sent', 'pending', 'sent', 'failed')),
  constraint homework_progress_answers_object_check check (jsonb_typeof(answers) = 'object'),
  constraint homework_progress_scores_check check (
    (score_correct is null or score_correct >= 0)
    and (score_total is null or score_total >= 0)
    and (score_correct is null or score_total is null or score_correct <= score_total)
    and (score_percent is null or score_percent between 0 and 100)
  ),
  constraint homework_progress_submission_dates_check check (
    status = 'draft' or (submitted_at is not null and locked_at is not null)
  ),
  constraint homework_progress_submitted_report_check check (
    status <> 'submitted' or report_status = 'sent'
  ),
  constraint homework_progress_report_sent_date_check check (
    report_status <> 'sent' or report_sent_at is not null
  )
);

create table if not exists public.vocabulary_progress (
  id bigint generated by default as identity primary key,
  student_id text not null,
  word_key text not null,
  status text not null default 'new',
  learned_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vocabulary_progress_student_word_key unique (student_id, word_key),
  constraint vocabulary_progress_status_check check (status in ('new', 'known', 'difficult')),
  constraint vocabulary_progress_learned_check check (status <> 'known' or learned_at is not null)
);

create table if not exists public.vocabulary_topic_progress (
  id bigint generated by default as identity primary key,
  student_id text not null,
  topic_id text not null,
  tests jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vocabulary_topic_progress_student_topic_key unique (student_id, topic_id),
  constraint vocabulary_topic_progress_tests_array_check check (jsonb_typeof(tests) = 'array')
);

create table if not exists public.grammar_progress (
  id bigint generated by default as identity primary key,
  student_id text not null,
  topic_id text not null,
  passed boolean not null default false,
  attempts integer not null default 0,
  best_score integer not null default 0,
  passed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint grammar_progress_student_topic_key unique (student_id, topic_id),
  constraint grammar_progress_attempts_check check (attempts >= 0),
  constraint grammar_progress_best_score_check check (best_score between 0 and 100),
  constraint grammar_progress_passed_date_check check (not passed or passed_at is not null)
);

create table if not exists public.telegram_recipients (
  id uuid primary key default gen_random_uuid(),
  student_id text not null unique,
  chat_id bigint not null unique,
  message_thread_id bigint,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.material_publications (
  id uuid primary key default gen_random_uuid(),
  student_id text not null,
  material_type text not null,
  material_id text not null,
  notification_version integer not null default 1,
  status text not null default 'pending',
  payload jsonb not null default '{}'::jsonb,
  telegram_message_id bigint,
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint material_publications_unique_notification unique (student_id, material_type, material_id, notification_version),
  constraint material_publications_status_check check (status in ('pending', 'sent', 'failed', 'skipped')),
  constraint material_publications_version_check check (notification_version > 0),
  constraint material_publications_payload_object_check check (jsonb_typeof(payload) = 'object'),
  constraint material_publications_sent_date_check check (status <> 'sent' or sent_at is not null)
);

create or replace function public.set_progress_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.prevent_homework_resubmission()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  request_role text := coalesce(current_setting('request.jwt.claim.role', true), '');
begin
  if old.status not in ('submitted_pending_report', 'submitted') then
    return new;
  end if;

  -- A browser using the anon role may never modify a locked submission.
  if request_role = 'anon' then
    raise exception 'Submitted homework is locked and cannot be changed.' using errcode = '42501';
  end if;

  if old.student_id is distinct from new.student_id
    or old.lesson_id is distinct from new.lesson_id
    or old.answers is distinct from new.answers
    or old.score_correct is distinct from new.score_correct
    or old.score_total is distinct from new.score_total
    or old.score_percent is distinct from new.score_percent
    or old.checked_at is distinct from new.checked_at
    or old.submitted_at is distinct from new.submitted_at
    or old.locked_at is distinct from new.locked_at
    or old.submission_id is distinct from new.submission_id
  then
    raise exception 'Final homework answers and result are immutable.' using errcode = '42501';
  end if;

  if old.status = 'submitted' then
    if new.status is distinct from old.status
      or new.report_status is distinct from old.report_status
      or new.report_sent_at is distinct from old.report_sent_at
      or new.report_error is distinct from old.report_error
    then
      raise exception 'A delivered homework report is immutable.' using errcode = '42501';
    end if;
    return new;
  end if;

  if new.status not in ('submitted_pending_report', 'submitted') then
    raise exception 'A locked homework submission cannot return to draft.' using errcode = '42501';
  end if;

  if new.status = 'submitted' and new.report_status <> 'sent' then
    raise exception 'Submitted status requires a sent report.' using errcode = '23514';
  end if;

  return new;
end;
$$;

-- Recreate triggers idempotently.
drop trigger if exists set_homework_progress_updated_at on public.homework_progress;
create trigger set_homework_progress_updated_at before update on public.homework_progress
for each row execute function public.set_progress_updated_at();

drop trigger if exists prevent_homework_resubmission on public.homework_progress;
create trigger prevent_homework_resubmission before update on public.homework_progress
for each row execute function public.prevent_homework_resubmission();

drop trigger if exists set_vocabulary_progress_updated_at on public.vocabulary_progress;
create trigger set_vocabulary_progress_updated_at before update on public.vocabulary_progress
for each row execute function public.set_progress_updated_at();

drop trigger if exists set_vocabulary_topic_progress_updated_at on public.vocabulary_topic_progress;
create trigger set_vocabulary_topic_progress_updated_at before update on public.vocabulary_topic_progress
for each row execute function public.set_progress_updated_at();

drop trigger if exists set_grammar_progress_updated_at on public.grammar_progress;
create trigger set_grammar_progress_updated_at before update on public.grammar_progress
for each row execute function public.set_progress_updated_at();

drop trigger if exists set_telegram_recipients_updated_at on public.telegram_recipients;
create trigger set_telegram_recipients_updated_at before update on public.telegram_recipients
for each row execute function public.set_progress_updated_at();

drop trigger if exists set_material_publications_updated_at on public.material_publications;
create trigger set_material_publications_updated_at before update on public.material_publications
for each row execute function public.set_progress_updated_at();

alter table public.homework_progress enable row level security;
alter table public.vocabulary_progress enable row level security;
alter table public.vocabulary_topic_progress enable row level security;
alter table public.grammar_progress enable row level security;
alter table public.telegram_recipients enable row level security;
alter table public.material_publications enable row level security;

-- Remove prior project policies so repeated execution is safe.
drop policy if exists "polina_homework_select" on public.homework_progress;
drop policy if exists "polina_homework_insert" on public.homework_progress;
drop policy if exists "polina_homework_update" on public.homework_progress;
create policy "polina_homework_select" on public.homework_progress for select to anon using (student_id = 'polina');
create policy "polina_homework_insert" on public.homework_progress for insert to anon with check (student_id = 'polina');
create policy "polina_homework_update" on public.homework_progress for update to anon using (student_id = 'polina') with check (student_id = 'polina');

drop policy if exists "polina_vocabulary_select" on public.vocabulary_progress;
drop policy if exists "polina_vocabulary_insert" on public.vocabulary_progress;
drop policy if exists "polina_vocabulary_update" on public.vocabulary_progress;
drop policy if exists "polina_vocabulary_delete" on public.vocabulary_progress;
create policy "polina_vocabulary_select" on public.vocabulary_progress for select to anon using (student_id = 'polina');
create policy "polina_vocabulary_insert" on public.vocabulary_progress for insert to anon with check (student_id = 'polina');
create policy "polina_vocabulary_update" on public.vocabulary_progress for update to anon using (student_id = 'polina') with check (student_id = 'polina');
create policy "polina_vocabulary_delete" on public.vocabulary_progress for delete to anon using (student_id = 'polina');

drop policy if exists "polina_vocabulary_topics_select" on public.vocabulary_topic_progress;
drop policy if exists "polina_vocabulary_topics_insert" on public.vocabulary_topic_progress;
drop policy if exists "polina_vocabulary_topics_update" on public.vocabulary_topic_progress;
drop policy if exists "polina_vocabulary_topics_delete" on public.vocabulary_topic_progress;
create policy "polina_vocabulary_topics_select" on public.vocabulary_topic_progress for select to anon using (student_id = 'polina');
create policy "polina_vocabulary_topics_insert" on public.vocabulary_topic_progress for insert to anon with check (student_id = 'polina');
create policy "polina_vocabulary_topics_update" on public.vocabulary_topic_progress for update to anon using (student_id = 'polina') with check (student_id = 'polina');
create policy "polina_vocabulary_topics_delete" on public.vocabulary_topic_progress for delete to anon using (student_id = 'polina');

drop policy if exists "polina_grammar_select" on public.grammar_progress;
drop policy if exists "polina_grammar_insert" on public.grammar_progress;
drop policy if exists "polina_grammar_update" on public.grammar_progress;
drop policy if exists "polina_grammar_delete" on public.grammar_progress;
create policy "polina_grammar_select" on public.grammar_progress for select to anon using (student_id = 'polina');
create policy "polina_grammar_insert" on public.grammar_progress for insert to anon with check (student_id = 'polina');
create policy "polina_grammar_update" on public.grammar_progress for update to anon using (student_id = 'polina') with check (student_id = 'polina');
create policy "polina_grammar_delete" on public.grammar_progress for delete to anon using (student_id = 'polina');

-- No public policies are created for the two server-only tables.
revoke all on table public.homework_progress from anon, authenticated;
revoke all on table public.vocabulary_progress from anon, authenticated;
revoke all on table public.vocabulary_topic_progress from anon, authenticated;
revoke all on table public.grammar_progress from anon, authenticated;
revoke all on table public.telegram_recipients from anon, authenticated;
revoke all on table public.material_publications from anon, authenticated;

grant select, insert, update on table public.homework_progress to anon;
grant select, insert, update, delete on table public.vocabulary_progress to anon;
grant select, insert, update, delete on table public.vocabulary_topic_progress to anon;
grant select, insert, update, delete on table public.grammar_progress to anon;

grant usage, select on sequence public.homework_progress_id_seq to anon;
grant usage, select on sequence public.vocabulary_progress_id_seq to anon;
grant usage, select on sequence public.vocabulary_topic_progress_id_seq to anon;
grant usage, select on sequence public.grammar_progress_id_seq to anon;

grant all on table public.homework_progress to service_role;
grant all on table public.vocabulary_progress to service_role;
grant all on table public.vocabulary_topic_progress to service_role;
grant all on table public.grammar_progress to service_role;
grant all on table public.telegram_recipients to service_role;
grant all on table public.material_publications to service_role;
grant usage, select on all sequences in schema public to service_role;
